apiVersion: 1
datasources:
  - name: MLflow DB
    uid: mlflow-db
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: mlflow
    secureJsonData:
      password: mlflow
    jsonData:
      database: mlflow
      sslmode: disable
      postgresVersion: 1600
    isDefault: true